### DISCUSSION TITLE
Training with Doclaynet and custom dataset

### DISCUSSION THREAD

**Discussion by yflam1** [deepdoctection/deepdoctection#161] [Q&A] [answered]
I read your tutorial and wrote the following script to fine-tune the given layout detection model using Doclaynet:

```python
import os
import deepdoctection as dd

cfg = dd.set_config_by_yaml("path/to/conf_dd_one.yaml")

doclaynet = dd.get_dataset("doclaynet")

config_yaml_path = dd.ModelCatalog.get_full_path_configs(cfg.CONFIG.D2LAYOUT)
weights_path = dd.ModelCatalog.get_full_path_weights(cfg.WEIGHTS.D2LAYOUT)
categories = dd.ModelCatalog.get_profile(cfg.WEIGHTS.D2LAYOUT).categories
layout_detector = dd.D2FrcnnDetector(config_yaml_path, weights_path, categories, device=cfg.DEVICE)
layout_service = dd.ImageLayoutService(layout_detector)

coco_metric = dd.get_metric("coco")

cat_to_sub_cat = doclaynet.dataflow.categories.get_sub_categories()
cat_to_sub_cat = {key:val[0] for key, val in cat_to_sub_cat.items()}
doclaynet.dataflow.categories.set_cat_to_sub_cat(cat_to_sub_cat)

config_overwrite=["SOLVER.MAX_ITER=100000",
                  "TEST.EVAL_PERIOD=20000",
                  "SOLVER.CHECKPOINT_PERIOD=20000",
                  "MODEL.BACKBONE.FREEZE_AT=0",
                  "SOLVER.BASE_LR=1e-3"]

build_train_config = ["max_datapoints=86000"]

dd.train_d2_faster_rcnn(
    path_config_yaml=config_yaml_path,
    dataset_train=doclaynet,
    path_weights=weights_path,
    config_overwrite=config_overwrite,
    log_dir="train_log",
    build_train_config=build_train_config,
    dataset_val=doclaynet,
    build_val_config=None,
    metric=coco_metric,
    pipeline_component_name="ImageLayoutService")
```

Here is my `conf_dd_one.yaml`:

```yaml
CONFIG:
  D2LAYOUT: dd/d2/layout/CASCADE_RCNN_R_50_FPN_GN.yaml
  D2CELL: dd/d2/cell/CASCADE_RCNN_R_50_FPN_GN.yaml
  D2ITEM: dd/d2/item/CASCADE_RCNN_R_50_FPN_GN.yaml
WEIGHTS:
  D2LAYOUT: layout/d2_model_0829999_layout_inf_only.pt
  D2CELL: cell/d2_model_1849999_cell_inf_only.pt
  D2ITEM: item/d2_model_1639999_item_inf_only.pt
LAYOUT_NMS_PAIRS:
  COMBINATIONS:
    - - text
      - table
    - - title
      - table
    - - text
      - list
    - - title
      - list
    - - text
      - title
    - - list
      - table
  THRESHOLDS:
    - 0.005
    - 0.005
    - 0.542
    - 0.1
    - 0.699
    - 0.01
SEGMENTATION:
  ASSIGNMENT_RULE: ioa
  IOA_THRESHOLD_ROWS: 0.4
  IOA_THRESHOLD_COLS: 0.4
  IOU_THRESHOLD_ROWS: 0.01
  IOU_THRESHOLD_COLS: 0.001
  REMOVE_IOU_THRESHOLD_ROWS: 0.001
  REMOVE_IOU_THRESHOLD_COLS: 0.001
  FULL_TABLE_TILING: True
  STRETCH_RULE: left
  USE_REFINEMENT: False
WORD_MATCHING:
  PARENTAL_CATEGORIES:
    - text
    - title
    - cell
    - list
    - figure
  CHILD_CATEGORIES:
    - word
  RULE: ioa
  IOA_THRESHOLD: 0.6
  IOU_THRESHOLD: 0.001
  MAX_PARENT_ONLY: False
TEXT_ORDERING:
  TEXT_CONTAINER: word
  FLOATING_TEXT_BLOCK:
    - title
    - text
    - list
    - figure
  TEXT_BLOCK:
    - title
    - text
    - list
    - cell
    - figure
    - header
    - body
  TEXT_CONTAINER_TO_TEXT_BLOCK: True
DEVICE: cuda
```

Is the script correct? And where will the fine-tuned model be saved?

Also, is it ok that I first fine-tune the given model using Doclaynet, and then fine-tune the fine-tuned model using my custom dataset?
