### DISCUSSION TITLE
How to run and test deepdoctection in Docker?

### DISCUSSION THREAD

**Discussion by rsoika** [deepdoctection/deepdoctection#282] [General]
Hi,
I did not yet understand how to test deepdoctection with the provided docker image. 

I created the following `docker-compose.yaml`  and `.env` file:

```
version: '3'
services:
  dd-gpu:
    image: deepdoctection/deepdoctection:v.0.29.0
    stdin_open: true
    tty: true
    volumes:
      #- ${CACHE_HOST}:${DEEPDOCTECTION_CACHE}
      - ${WORK_DIR}:/home/files
```

.env:

```
CACHE_HOST="/home/test/deepdoctection/cache"
WORK_DIR="/home/test/deepdoctection/workdir"
```

I can start the container successfully with `docker compose up` but I did not understand how to test the framework. Just copy .pdf files into the WORK_DIR did not trigger anything. 

What is needed to analyze a pdf test file?

Thanks for any hints. 

===
Ralph
