### ISSUE TITLE
Request : How to define the layout segment order?

### ISSUE THREAD

**Issue by Fruit-GG** [deepdoctection/deepdoctection#382]
Dear all,
Recently, I've been working on an OCR project dealing with scientific papers. These papers typically come in a two-column format. However, I've noticed that the order in which the text is segmented during the OCR process doesn't match the way we usually read. I'm wondering if there are any methods to modify the underlying ordering principle to make it more in line with our reading habits. Any insights or suggestions would be greatly appreciated.
![viz_0_current](https://github.com/user-attachments/assets/bcc0fdd8-dc90-4568-b2fc-d3ba76a08f62)
![viz_0_target](https://github.com/user-attachments/assets/dadd1fe6-1061-46bb-a736-947521b37652)

**Comment by JaMe76** [comment]
Hi,

the [reading order](https://deepdoctection.readthedocs.io/en/latest/tutorials/layout_parsing_structure/) for text blocks is going to be determined by a (complicated) algorithm that divides a page into columns and vertical blocks.

Some configuration can be changed in the `.yaml` file:

```yaml
TEXT_ORDERING:
  TEXT_BLOCK_CATEGORIES:
    - title
    - text
    - list
    - cell
    - column_header
    - projected_row_header
    - spanning
    - row_header
  FLOATING_TEXT_BLOCK_CATEGORIES:
    - title
    - text
    - list
  INCLUDE_RESIDUAL_TEXT_CONTAINER: False
  STARTING_POINT_TOLERANCE: 0.005
  BROKEN_LINE_TOLERANCE: 0.003
  HEIGHT_TOLERANCE: 2.0
  PARAGRAPH_BREAK: 0.035
```

Docs about these parameters can be found [here](https://deepdoctection.readthedocs.io/en/latest/modules/deepdoctection.pipe/#deepdoctection.pipe.order.TextOrderService).

If there is a chance to upload this documents I can also have a look to check what might be going wrong. The algorithm should be able to return a correct reading order.
